name: RAG_ARCHITECTURE
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - nltk
  - scikit-learn
  - sentence-transformers
  - numpy
  - jupyter
  - python-dotenv
  - pip
  - pip:
      - openai
      - pinecone-client
      - nemoguardrails
      - datasets
      - langchain
      - pypdf
